# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='\u0424.\u0418.\u041e')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='experts/', verbose_name='\u0424\u043e\u0442\u043e')),
            ],
            options={
                'verbose_name': '\u042d\u043a\u0441\u043f\u0435\u0440\u0442',
                'verbose_name_plural': '\u042d\u043a\u0441\u043f\u0435\u0440\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('material', models.FileField(upload_to='documents/', verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b')),
            ],
            options={
                'verbose_name': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b',
                'verbose_name_plural': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044b',
            },
        ),
    ]
