# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fes', '0002_experts_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experts',
            name='photo',
            field=models.ImageField(upload_to='experts/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
