# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fes', '0003_auto_20161012_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='position',
            field=models.CharField(default=99, max_length=10, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043a\u043e\u0432\u044b\u0439 \u043d\u043e\u043c\u0435\u0440'),
        ),
    ]
