# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160704_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='center_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regionsmap.Centers', verbose_name='\u0426\u0435\u043d\u0442\u0440'),
        ),
    ]
