# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160704_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('document', models.ImageField(upload_to='events_documents/', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442(\u0421\u043e\u0431\u044b\u0442\u0438\u044f)',
                'verbose_name_plural': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b(\u0421\u043e\u0431\u044b\u0442\u0438\u044f)',
            },
        ),
    ]
