# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='#', max_length=250, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('title', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0446\u0435\u043d\u0442\u0440\u0430')),
                ('image', models.ImageField(blank=True, upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('desc', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('director', models.CharField(blank=True, max_length=250, verbose_name='\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
                ('sub_director', models.CharField(blank=True, max_length=250, verbose_name='\u0417\u0430\u043c\u0435\u0441\u0442\u0438\u0442\u0435\u043b\u044c')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u0426\u0435\u043d\u0442\u0440',
                'verbose_name_plural': '\u0426\u0435\u043d\u0442\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('key', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='\u041a\u043e\u0434')),
                ('title', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': '\u0420\u0435\u0433\u0438\u043e\u043d',
                'verbose_name_plural': '\u0420\u0435\u0433\u0438\u043e\u043d\u044b',
            },
        ),
        migrations.AddField(
            model_name='centers',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regionsmap.Regions'),
        ),
    ]
