# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionsmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='title',
            field=models.CharField(max_length=400, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0446\u0435\u043d\u0442\u0440\u0430'),
        ),
    ]
