# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('regionsmap', '0003_centers_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='account_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
        migrations.AlterField(
            model_name='centers',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u043a\u043a\u0430\u0443\u043d\u0442 \u0446\u0435\u043d\u0442\u0440\u0430'),
        ),
    ]
