# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regionsmap', '0004_auto_20160725_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centers',
            name='account_group',
        ),
    ]
