# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regionsmap', '0005_remove_centers_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u043a\u043a\u0430\u0443\u043d\u0442 \u0446\u0435\u043d\u0442\u0440\u0430'),
        ),
    ]
