# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regionsmap', '0006_auto_20160726_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regionsmap.Regions'),
        ),
    ]
