# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionsmap', '0008_centers_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='dobro_link',
            field=models.CharField(default='#', max_length=350, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443 \u0434\u043e\u0431\u043e\u0432\u043e\u043b\u044c\u0446\u044b.\u0440\u0444'),
        ),
    ]
