# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20160627_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='lable',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
