# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter_lable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='lable',
            new_name='label',
        ),
    ]
