# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0005_auto_20160704_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u0440\u0438\u0432\u044f\u0437\u0430\u0442\u044c \u0430\u043a\u043a\u0430\u0443\u043d\u0442 \u0434\u043b\u044f \u0446\u0435\u043d\u0442\u0440\u0430'),
        ),
    ]
