# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_newsletter_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='account',
        ),
    ]
