# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20160804_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='rubric',
        ),
    ]
