# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_remove_newsletter_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='rubric',
            field=models.CharField(blank=True, choices=[('WCS', '\u0427\u0435\u043c\u043f\u0438\u043e\u043d\u0430\u0442 \u043c\u0438\u0440\u0430')], max_length=20, null=True, verbose_name='\u0420\u0443\u0431\u0440\u0438\u043a\u0430'),
        ),
    ]
