# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_newsletter_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0440\u0443\u0431\u0440\u0438\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0420\u0443\u0431\u0440\u0438\u043a\u0430',
                'verbose_name_plural': '\u0420\u0443\u0431\u0440\u0438\u043a\u0438',
            },
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.Rubrics', verbose_name='\u0420\u0443\u0431\u0440\u0438\u043a\u0430'),
        ),
    ]
