# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_remove_partners_teamwork'),
        ('newsletter', '0013_auto_20160809_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='news_docments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Documents', verbose_name='\u041f\u0440\u0438\u043a\u0440\u0435\u043f\u0438\u0442\u044c \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442'),
        ),
    ]
