# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_newsletter_news_docments'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='fes_news',
            field=models.BooleanField(default=False, verbose_name='\u041d\u043e\u0432\u043e\u0441\u0442\u044c \u0424\u0435\u0434\u0435\u0440\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u044d\u043a\u0441\u043f\u0435\u0440\u0442\u043d\u043e\u0433\u043e \u0441\u043e\u0432\u0435\u0442\u0430'),
        ),
    ]
