# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='\u041c\u043e\u0441\u043a\u0432\u0430', max_length=100, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('address', models.CharField(max_length=250, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('metro', models.CharField(max_length=100, verbose_name='\u0421\u0442\u0430\u043d\u0446\u0438\u044f \u043c\u0435\u0442\u0440\u043e')),
                ('phone', models.CharField(max_length=20, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='\u0418\u043d\u0434\u0435\u043a\u0441')),
                ('map_con', models.TextField(blank=True, verbose_name='\u041a\u0430\u0440\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('struc_soviet', models.CharField(choices=[('sov', '\u0421\u043e\u0432\u0435\u0442'), ('dir', '\u0414\u0438\u0440\u0435\u043a\u0446\u0438\u044f')], default='sov', max_length=4, verbose_name='\u041e\u0442\u043d\u043e\u0441\u0438\u0442\u0441\u044f \u043a')),
                ('img', imagekit.models.fields.ProcessedImageField(upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0430\u043d\u0438\u0435')),
                ('full_name', models.CharField(max_length=200, verbose_name='\u0424.\u0418.\u041e.')),
                ('is_major', models.BooleanField(default=False, verbose_name='\u0414\u0438\u0440\u0435\u043a\u0442\u043e\u0440/\u0433\u043b\u0430\u0432\u0430 \u0441\u043e\u0432\u0435\u0442\u0430')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f')),
                ('desc', models.CharField(max_length=200, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('about', models.TextField(verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0427\u043b\u0435\u043d \u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u044b',
                'verbose_name_plural': '\u0427\u043b\u0435\u043d\u044b \u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u044b',
            },
        ),
    ]
