# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
        ),
    ]
