# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademySlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('photo', models.ImageField(upload_to='academy_exprets/', verbose_name='\u0424\u043e\u0442\u043e')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e(\u0441\u043b\u0430\u0439\u0434\u0435\u0440)',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e(\u0441\u043b\u0430\u0439\u0434\u0435\u0440)',
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='\u0424.\u0418.\u041e')),
                ('photo', models.ImageField(upload_to='experts/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('desc', models.CharField(blank=True, max_length=300, verbose_name='\u0412\u0438\u0434 \u0434\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438')),
            ],
            options={
                'verbose_name': '\u042d\u043a\u0441\u043f\u0435\u0440\u0442',
                'verbose_name_plural': '\u042d\u043a\u0441\u043f\u0435\u0440\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('video', models.CharField(max_length=600, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0432\u0438\u0434\u0435\u043e-\u0440\u0435\u0441\u0443\u0440\u0441')),
                ('lecture', models.FileField(upload_to='documents/', verbose_name='\u041b\u0435\u043a\u0446\u0438\u044f')),
                ('presentation', models.FileField(upload_to='documents/', verbose_name='\u041f\u0440\u0435\u0437\u0435\u043d\u0442\u0430\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b',
                'verbose_name_plural': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('teacher', models.CharField(max_length=350, verbose_name='\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c')),
                ('webinar', models.CharField(max_length=600, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0432\u0435\u0431\u0438\u043d\u0430\u0440')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0412\u0435\u0431\u0438\u043d\u0430\u0440',
                'verbose_name_plural': '\u0412\u0435\u0431\u0438\u043d\u0430\u0440\u044b',
            },
        ),
    ]
