# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 09:45
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_webinars_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinars',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='webinars', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
