# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_history_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
    ]
