# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_history_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='quote',
            field=models.TextField(blank=True, verbose_name='\u0426\u0438\u0442\u0430\u0442\u0430'),
        ),
    ]
