# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 19:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_opinion_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='\u0418\u0441\u0442\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='\u041c\u043d\u0435\u043d\u0438\u0435'),
        ),
    ]
