# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20160628_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='position',
            field=models.IntegerField(default=1, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f'),
        ),
    ]
