# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20160704_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='lable',
            new_name='label',
        ),
    ]
