# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20160707_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('source', models.CharField(max_length=250, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0412\u0438\u0434\u0435\u043e(\u0414\u043b\u044f \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b)',
                'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e(\u0414\u043b\u044f \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b)',
            },
        ),
    ]
