# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 12:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_videohomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='teamwork',
            field=ckeditor.fields.RichTextField(default='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442', verbose_name='\u0412\u0437\u0430\u0438\u043c\u043e\u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435'),
        ),
    ]
