# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_partners_teamwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='teamwork',
        ),
    ]
