# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
    ]
