# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0003_auto_20160629_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumphoto',
            name='description',
        ),
    ]
