# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 21:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0004_remove_albumphoto_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0430\u043b\u044c\u0431\u043e\u043c\u0430'),
        ),
    ]
